#!/usr/bin/env python3
"""
Automated setup script for WhatsApp Bot deployment
This script helps configure and deploy the bot for production use.
"""

import os
import sys
import subprocess
import json
import shutil
from pathlib import Path


def print_header(text):
    """Print a formatted header"""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def print_step(step_num, total, text):
    """Print a step indicator"""
    print(f"\n[{step_num}/{total}] {text}")
    print("-" * 40)


def run_command(command, description=""):
    """Run a shell command and return success status"""
    if description:
        print(f"Running: {description}")
    
    try:
        result = subprocess.run(
            command,
            shell=True,
            check=True,
            capture_output=True,
            text=True
        )
        print("✓ Success")
        return True
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed: {e.stderr}")
        return False


def check_requirements():
    """Check if required software is installed"""
    print_step(1, 7, "Checking Requirements")
    
    # Check Python
    print("Checking Python...")
    try:
        import sys
        version = sys.version_info
        if version.major >= 3 and version.minor >= 6:
            print(f"✓ Python {version.major}.{version.minor}.{version.micro} found")
        else:
            print("✗ Python 3.6+ required")
            return False
    except:
        print("✗ Python not found")
        return False
    
    # Check Node.js
    print("\nChecking Node.js...")
    result = subprocess.run(
        "node --version",
        shell=True,
        capture_output=True,
        text=True
    )
    if result.returncode == 0:
        print(f"✓ Node.js {result.stdout.strip()} found")
    else:
        print("✗ Node.js not found. Install from https://nodejs.org")
        return False
    
    # Check npm
    print("\nChecking npm...")
    result = subprocess.run(
        "npm --version",
        shell=True,
        capture_output=True,
        text=True
    )
    if result.returncode == 0:
        print(f"✓ npm {result.stdout.strip()} found")
    else:
        print("✗ npm not found")
        return False
    
    return True


def install_python_deps():
    """Install Python dependencies"""
    print_step(2, 7, "Installing Python Dependencies")
    
    return run_command(
        f"{sys.executable} -m pip install -r requirements.txt",
        "Installing packages from requirements.txt"
    )


def install_node_deps():
    """Install Node.js dependencies"""
    print_step(3, 7, "Installing Node.js Dependencies")
    
    return run_command(
        "npm install",
        "Installing packages from package.json"
    )


def create_config():
    """Create configuration file"""
    print_step(4, 7, "Creating Configuration File")
    
    if os.path.exists("wa_config.py"):
        response = input("wa_config.py already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Skipping configuration creation")
            return True
    
    print("\nLet's configure your bot:")
    print("(Press Enter to use default values)")
    
    # Get user input
    owner_phone = input("\nYour phone number (with country code, e.g., 14155551234): ").strip()
    if not owner_phone:
        print("✗ Phone number is required")
        return False
    
    owner_name = input("Your name (e.g., John Doe): ").strip() or "Bot Owner"
    
    session_name = input("Session name (default: whatsapp-bot-session): ").strip() or "whatsapp-bot-session"
    
    db_uri = input("\nDatabase URI (default: sqlite:///bot.db): ").strip() or "sqlite:///bot.db"
    
    # Format phone number
    if not owner_phone.endswith("@c.us"):
        owner_phone = f"{owner_phone}@c.us"
    
    # Create config file
    config_content = f'''"""
WhatsApp Bot Configuration
Auto-generated by setup script
"""

class WhatsAppConfig:
    """WhatsApp Bot Configuration"""
    
    # REQUIRED
    OWNER_ID = "{owner_phone}"
    OWNER_NAME = "{owner_name}"
    SESSION_NAME = "{session_name}"
    
    # PLATFORM
    PLATFORM = "whatsapp"
    
    # DATABASE
    SQLALCHEMY_DATABASE_URI = "{db_uri}"
    MESSAGE_DUMP = None
    
    # MODULE LOADING
    LOAD = []
    NO_LOAD = ['translation', 'rss']
    
    # OPTIONAL
    SUDO_USERS = ["{owner_phone}"]  # Add trusted users here
    SUPPORT_USERS = []
    WHITELIST_USERS = []
    DONATION_LINK = None
    DEL_CMDS = False
    STRICT_GBAN = False
    WORKERS = 8
    
    # WhatsApp Specific
    WHATSAPP_QR_TERMINAL = True
    WHATSAPP_HEADLESS = True
    
    # Features
    ENABLE_STICKERS = True
    ENABLE_MEDIA = True
    ENABLE_VOICE = True


class Production(WhatsAppConfig):
    LOGGER = False


class Development(WhatsAppConfig):
    LOGGER = True
'''
    
    try:
        with open("wa_config.py", "w") as f:
            f.write(config_content)
        print("\n✓ Configuration file created: wa_config.py")
        return True
    except Exception as e:
        print(f"\n✗ Failed to create config: {e}")
        return False


def run_tests():
    """Run test suite"""
    print_step(5, 7, "Running Tests")
    
    return run_command(
        f"{sys.executable} tests/test_bot_core.py",
        "Running bot core tests"
    )


def create_systemd_service():
    """Create systemd service files for Linux"""
    print_step(6, 7, "Creating Service Files (Optional)")
    
    if sys.platform != "linux":
        print("Systemd services are only for Linux. Skipping...")
        return True
    
    response = input("Create systemd service files? (y/N): ")
    if response.lower() != 'y':
        print("Skipping service creation")
        return True
    
    current_dir = os.getcwd()
    python_path = sys.executable
    
    # Bridge service
    bridge_service = f'''[Unit]
Description=WhatsApp Bot Bridge
After=network.target

[Service]
Type=simple
User={os.getenv("USER")}
WorkingDirectory={current_dir}
ExecStart=/usr/bin/node {current_dir}/whatsapp_bridge.js
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
'''
    
    # Bot service
    bot_service = f'''[Unit]
Description=WhatsApp Bot
After=network.target whatsapp-bridge.service
Requires=whatsapp-bridge.service

[Service]
Type=simple
User={os.getenv("USER")}
WorkingDirectory={current_dir}
ExecStart={python_path} {current_dir}/whatsapp_bot.py
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
'''
    
    try:
        with open("whatsapp-bridge.service", "w") as f:
            f.write(bridge_service)
        with open("whatsapp-bot.service", "w") as f:
            f.write(bot_service)
        
        print("\n✓ Service files created:")
        print("  - whatsapp-bridge.service")
        print("  - whatsapp-bot.service")
        print("\nTo install:")
        print("  sudo cp whatsapp-*.service /etc/systemd/system/")
        print("  sudo systemctl daemon-reload")
        print("  sudo systemctl enable whatsapp-bridge whatsapp-bot")
        print("  sudo systemctl start whatsapp-bridge whatsapp-bot")
        
        return True
    except Exception as e:
        print(f"\n✗ Failed to create services: {e}")
        return False


def create_docker_files():
    """Create Docker configuration"""
    print_step(7, 7, "Creating Docker Files (Optional)")
    
    response = input("Create Docker configuration? (y/N): ")
    if response.lower() != 'y':
        print("Skipping Docker configuration")
        return True
    
    # Dockerfile
    dockerfile = '''FROM node:16-alpine as bridge
WORKDIR /bridge
COPY package*.json ./
RUN npm install
COPY whatsapp_bridge.js ./

FROM python:3.9-slim
WORKDIR /app

# Install Node.js
COPY --from=bridge /usr/local/bin/node /usr/local/bin/
COPY --from=bridge /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .
COPY --from=bridge /bridge /app/bridge

# Expose ports
EXPOSE 3000 5000

# Start script
CMD ["sh", "-c", "cd bridge && node whatsapp_bridge.js & python whatsapp_bot.py"]
'''
    
    # docker-compose.yml
    docker_compose = '''version: '3.8'

services:
  whatsapp-bridge:
    build: .
    container_name: whatsapp-bridge
    ports:
      - "3000:3000"
    volumes:
      - ./.wwebjs_auth:/app/bridge/.wwebjs_auth
    restart: unless-stopped

  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    depends_on:
      - whatsapp-bridge
    environment:
      - BRIDGE_URL=http://whatsapp-bridge:3000
    volumes:
      - ./wa_config.py:/app/wa_config.py
      - ./bot.db:/app/bot.db
    restart: unless-stopped
'''
    
    # .dockerignore
    dockerignore = '''__pycache__/
*.py[cod]
*$py.class
.git/
.gitignore
*.md
tests/
.wwebjs_auth/
venv/
env/
.env
*.log
'''
    
    try:
        with open("Dockerfile", "w") as f:
            f.write(dockerfile)
        with open("docker-compose.yml", "w") as f:
            f.write(docker_compose)
        with open(".dockerignore", "w") as f:
            f.write(dockerignore)
        
        print("\n✓ Docker files created:")
        print("  - Dockerfile")
        print("  - docker-compose.yml")
        print("  - .dockerignore")
        print("\nTo run:")
        print("  docker-compose up -d")
        
        return True
    except Exception as e:
        print(f"\n✗ Failed to create Docker files: {e}")
        return False


def print_next_steps():
    """Print next steps for the user"""
    print_header("Setup Complete!")
    
    print("✓ All dependencies installed")
    print("✓ Configuration created")
    print("✓ Tests passed")
    print("\nNext Steps:")
    print("\n1. Start the WhatsApp Bridge:")
    print("   Terminal 1: npm start")
    print("\n2. Start the Bot:")
    print("   Terminal 2: python whatsapp_bot.py")
    print("\n3. Scan the QR code with WhatsApp")
    print("\n4. Send a message to the bot: /start")
    print("\nFor more information:")
    print("  - Setup guide: SETUP.md")
    print("  - Quick start: QUICKSTART.md")
    print("  - User guide: USER_GUIDE.md")
    print("\n" + "=" * 60)


def main():
    """Main setup function"""
    print_header("WhatsApp Bot Setup Script")
    
    print("This script will help you set up the WhatsApp bot.")
    print("It will:")
    print("  1. Check requirements")
    print("  2. Install dependencies")
    print("  3. Create configuration")
    print("  4. Run tests")
    print("  5. (Optional) Create service files")
    print("  6. (Optional) Create Docker configuration")
    
    response = input("\nContinue? (Y/n): ")
    if response.lower() == 'n':
        print("Setup cancelled")
        return
    
    # Run setup steps
    steps = [
        check_requirements,
        install_python_deps,
        install_node_deps,
        create_config,
        run_tests,
        create_systemd_service,
        create_docker_files
    ]
    
    for step in steps:
        if not step():
            print("\n✗ Setup failed at step: " + step.__name__)
            print("Please fix the error and run the script again.")
            sys.exit(1)
    
    print_next_steps()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n✗ Unexpected error: {e}")
        sys.exit(1)
